packages:
  - apps/*
  - packages/*

catalog:
  # Storybook
  "@storybook/addon-a11y": "^10.1.11"
  "@storybook/addon-docs": "10.1.11"
  "@storybook/addon-onboarding": "10.1.11"
  "@storybook/addon-vitest": "^10.1.11"
  "@storybook/react-vite": "^10.1.11"
  "@chromatic-com/storybook": "^4.1.3"
  eslint-plugin-storybook: "10.1.11"
  storybook: "10.1.11"
  msw-storybook-addon: "^2.0.4"

ignoredBuiltDependencies:
  - msw

onlyBuiltDependencies:
  - esbuild
