name: Admin Deployment (dev)
on:
  push:
    branches:
      - main
    paths:
      - "apps/admin/**"
      - "package.json"
      - "packages/**"
      - "pnpm-lock.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "apps/admin/**"
      - "package.json"
      - "packages/**"
      - "pnpm-lock.yaml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    name: Admin Deployment (dev)
    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ github.event_name == 'pull_request' && 'admin-preview' || 'admin-dev'}}
      mode: development
      deployment_url: https://${{ github.event_name == 'pull_request' && 'admin-preview' || 'admin-dev'}}.passu.sssupport.shop
      dist_directory: apps/admin/dist
