name: User Deployment (dev)
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "apps/user/**"
      - "package.json"
      - "packages/**"
      - "pnpm-lock.yaml"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "apps/user/**"
      - "package.json"
      - "packages/**"
      - "pnpm-lock.yaml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    name: User Deployment (dev)
    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ github.event_name == 'pull_request' && 'preview' || 'dev'}}
      mode: development
      deployment_url: https://${{ github.event_name == 'pull_request' && 'preview' || 'dev'}}.passu.sssupport.shop
      dist_directory: apps/user/dist
